-- Central-server schema for a fresh PostgreSQL database.
-- Text timestamps and JSON preserve the values stored by the SQLite prototype.
CREATE TABLE hosts (
    host_id text PRIMARY KEY,
    last_heartbeat_utc text NOT NULL
);

CREATE TABLE terminals (
    host_id text NOT NULL,
    terminal_id text NOT NULL,
    data_path text NOT NULL,
    last_seen_utc text NOT NULL,
    PRIMARY KEY (host_id, terminal_id)
);

CREATE TABLE log_events (
    event_id text PRIMARY KEY,
    host_id text NOT NULL,
    terminal_id text NOT NULL,
    stream text NOT NULL,
    file_name text NOT NULL,
    generation bigint NOT NULL,
    byte_offset bigint NOT NULL,
    raw_line text NOT NULL,
    received_utc text NOT NULL,
    UNIQUE (host_id, terminal_id, stream, file_name, generation, byte_offset)
);
CREATE INDEX idx_log_events_received ON log_events(received_utc DESC);
CREATE INDEX idx_log_events_terminal_received
    ON log_events(host_id, terminal_id, received_utc DESC);

CREATE TABLE collector_heartbeats (
    heartbeat_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id text NOT NULL,
    received_utc text NOT NULL,
    observed_at_utc text NOT NULL,
    pending_count bigint NOT NULL,
    payload_json text NOT NULL
);
CREATE INDEX idx_heartbeats_host_latest
    ON collector_heartbeats(host_id, heartbeat_id DESC);

CREATE TABLE alerts (
    host_id text NOT NULL,
    alert_type text NOT NULL,
    target text NOT NULL,
    state text NOT NULL,
    detail text NOT NULL,
    changed_utc text NOT NULL,
    last_attempt_utc text,
    last_sent_utc text,
    active_notified bigint NOT NULL DEFAULT 0,
    last_error text,
    PRIMARY KEY (host_id, alert_type, target)
);

CREATE TABLE terminal_status (
    host_id text NOT NULL,
    terminal_id text NOT NULL,
    data_path text NOT NULL,
    observed_at_utc text NOT NULL,
    received_utc text NOT NULL,
    status_json text NOT NULL,
    PRIMARY KEY (host_id, terminal_id)
);

CREATE TABLE accounts (
    server text NOT NULL,
    login bigint NOT NULL,
    currency text NOT NULL,
    day_timezone text NOT NULL,
    host_id text NOT NULL,
    terminal_id text NOT NULL,
    latest_snapshot_utc text NOT NULL,
    history_start_day text NOT NULL,
    balance text,
    PRIMARY KEY (server, login)
);

CREATE TABLE positions (
    server text NOT NULL,
    login bigint NOT NULL,
    ticket bigint NOT NULL,
    symbol text NOT NULL,
    type bigint NOT NULL,
    magic bigint NOT NULL,
    strategy text NOT NULL,
    volume double precision NOT NULL,
    price_open double precision NOT NULL,
    price_current double precision NOT NULL,
    profit text NOT NULL,
    swap text NOT NULL,
    comment text NOT NULL,
    PRIMARY KEY (server, login, ticket)
);

CREATE TABLE deals (
    server text NOT NULL,
    login bigint NOT NULL,
    ticket bigint NOT NULL,
    time_utc text NOT NULL,
    day_local text NOT NULL,
    type bigint NOT NULL,
    kind text NOT NULL,
    entry bigint NOT NULL,
    position_id bigint NOT NULL,
    symbol text NOT NULL,
    magic bigint NOT NULL,
    strategy text NOT NULL,
    comment text NOT NULL,
    profit text NOT NULL,
    commission text NOT NULL,
    swap text NOT NULL,
    fee text NOT NULL,
    volume double precision NOT NULL DEFAULT 0,
    PRIMARY KEY (server, login, ticket)
);
CREATE INDEX idx_deals_account_day ON deals(server, login, day_local);

CREATE TABLE backtest_runs (
    run_id text PRIMARY KEY,
    strategy text NOT NULL,
    file_name text NOT NULL,
    file_hash text NOT NULL UNIQUE,
    currency text NOT NULL,
    starting_capital text NOT NULL,
    first_day text NOT NULL,
    last_day text NOT NULL,
    row_count integer NOT NULL,
    imported_utc text NOT NULL
);

CREATE TABLE backtest_days (
    run_id text NOT NULL REFERENCES backtest_runs(run_id) ON DELETE CASCADE,
    day text NOT NULL,
    net_pnl text NOT NULL,
    PRIMARY KEY (run_id, day)
);
CREATE INDEX idx_backtest_days_day ON backtest_days(day);

CREATE TABLE close_alert_baselines (
    server text NOT NULL,
    login bigint NOT NULL,
    initialized_utc text NOT NULL,
    PRIMARY KEY (server, login)
);

CREATE TABLE close_notifications (
    server text NOT NULL,
    login bigint NOT NULL,
    ticket bigint NOT NULL,
    state text NOT NULL,
    created_utc text NOT NULL,
    last_attempt_utc text,
    sent_utc text,
    last_error text,
    PRIMARY KEY (server, login, ticket)
);
